cmake and bmk fixes (#4)
* benchmark: remove optimus.ops

Remove unused packet.

Signed-off-by: Xuan Zhuo <xuanzhuo@linux.alibaba.com>

* build: add rt

This project uses the librt interfaces, such as the shm_open family of
functions. In some Linux distributions, librt has already been merged
into glibc, so the rt library is not explicitly needed. However, in some
other distributions, linking errors may occur, such as the one shown
below. By adding -lrt during linking, we can ensure better compatibility
across different systems. This does not cause any problems on
distributions where librt is already included in glibc, as the required
symbols are still accessible.

/usr/bin/ld: ../../libaf.a(van.cc.o): undefined reference to symbol 'shm_open@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Signed-off-by: Xuan Zhuo <xuanzhuo@linux.alibaba.com>

---------

Signed-off-by: Xuan Zhuo <xuanzhuo@linux.alibaba.com>